WIP: Multiplatform implementation
walleth/keccak pull request #7
Opened 2019-04-09 12:52 UTC by RiccardoM

### Changes
- Changed the whole code architecture in order to allow multiplatform usage of the library. 

### Additions
- Added the `ripemd160` module
- Added the `keccak` module
- Added the `extensions` module

### Removals
- I had to remove Gradle Witness as I don't know how to make it work inside multiplatform projects

2019-04-09 13:31 UTC, rmontagnin commented
All the tests should pass correctly and the PR should be ready to be merged

2019-04-09 14:23 UTC, ligi requested changes

2019-04-09 14:23 UTC, ligi commented on README.md
> +   - Heavily based on this java implementation: [@romus/sha](https://github.com/romus/sha)
following 2 lines belong to SHA-3 not SHA.2

2019-04-09 16:11 UTC, RiccardoM commented on README.md
> +   - Heavily based on this java implementation: [@romus/sha](https://github.com/romus/sha)
Updated

2019-04-09 16:22 UTC, ligi approved these changes
I see failing tests:


```
khash.sha256.Sha256Tests > testHashRawBytes FAILED
    java.lang.AssertionError at Sha256Tests.kt:36

khash.sha256.Sha256Tests > testDigest FAILED
    java.lang.AssertionError at Sha256Tests.kt:26


```

2019-04-09 17:30 UTC, RiccardoM commented
> I see failing tests:
> 
> ```
> khash.sha256.Sha256Tests > testHashRawBytes FAILED
>     java.lang.AssertionError at Sha256Tests.kt:36
> 
> khash.sha256.Sha256Tests > testDigest FAILED
>     java.lang.AssertionError at Sha256Tests.kt:26
> ```

Should be fixed now. I think this was due to a wrong [`mockkObject`](https://mockk.io/#object-mocks) call that made the `Sha256` object return a different result in subsequent tests. With the last commit this should be fixed.

2019-04-09 19:22 UTC, merged

2019-04-09 21:19 UTC, ligi commented
dam - just saw now after the merge that the module structure is wrong - sha256 is in sha3 - this is wrong - can you fix @RiccardoM

2019-04-10 05:20 UTC, RiccardoM commented
@ligi Implemented the fix inside GH-8